### ISSUE TITLE
Signature Validation in Response can be Bypassed

### ISSUE THREAD

**Issue by SaneBow** [fzlee/alipay#69]
### Issue
At [line 551](https://github.com/fzlee/alipay/blob/a53231a10587667d519e06bdcb57466d50426838/alipay/__init__.py#L551) in the function `_verify_and_return_sync_response()`, the raw response string is passed to `_get_string_to_be_signed()`, which parses the value of the first occurrence of `response_type` for signature validation. However, the result returned is from the dict converted by `json.loads` before the signature check. The inconsistency between the value-of-use and value-of-check can lead to signature validation bypass and response forgery.

### Proof-of-Concept
<img width="1435" alt="fzlee-alipay-poc" src="https://user-images.githubusercontent.com/5907249/50749167-22290580-1278-11e9-8c49-9e4b60018411.png">

Explain: Only the last value of duplicated keys in python dict will be preserved. The original response says the amount of the order is 0.04, while the library takes the forged amount of 100 as result. 

### Impact
The signature validation in response message can be totally bypassed. Attackers may be able to forge returned data without the private key.

### Recommended Fix
Replace `return result` with `return {response_type: json.loads(raw_string)}`.

**Comment by fzlee** [comment]
Hi SaneBow:
Many thanks for your information. 

`_verify_and_return_sync_response` should be used with direct Alipay api calls instead of Alipay payment callback validation.
Since HTTPS is enabled on alipay gateway, I think something like MITM via HTTPS is mandantary for these kind of attacks.

No matter what, we are still facing those kind of potential risks, and changes will be made on your suggestion soon.

**Comment by SaneBow** [comment]
@fzlee I agree. This is a low-risk issue. However, it's also easy to fix.

**Comment by fzlee** [comment]
version 1.9 uploaded
